/* USER */
export const LOGIN_USER = "LOGIN_USER";
export const SET_USER = "SET_USER";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const LOAD_USER = "LOAD_USER";
export const LOGOUT = "LOGOUT";

/* JOBS */
export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";
export const FILTERED_JOBS = "FILTERED_JOBS";
export const CLEAR_USER_JOB_FILTER_SELECTIONS =
  "CLEAR_USER_JOB_FILTER_SELECTIONS";

/* SKILLS AND LOCATIONS AND REMOTE*/
export const UPDATE_SKILLS_SEARCH_TERM = "UPDATE_SKILLS_SEARCH_TERM";
export const INCLUDE_JOB_BY_SKILL = "INCLUDE_JOB_BY_SKILL";
export const UPDATE_LOCATIONS_SEARCH_TERM = "UPDATE_LOCATIONS_SEARCH_TERM";
export const INCLUDE_JOB_BY_LOCATION = "INCLUDE_JOB_BY_LOCATION";
export const UPDATE_REMOTE_SEARCH_TERM = "UPDATE_REMOTE_SEARCH_TERM";
export const INCLUDE_JOB_BY_REMOTE = "INCLUDE_JOB_BY_REMOTE";

/* ORGANIZATIONS */
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";
export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION";

/* JOB TYPES */
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES";
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES";
export const INCLUDE_JOB_BY_JOB_TYPE = "INCLUDE_JOB_BY_JOB_TYPE";

/* DEGREES */
export const UNIQUE_DEGREES = "UNIQUE_DEGREES";
export const ADD_SELECTED_DEGREES = "ADD_SELECTED_DEGREES";
export const INCLUDE_JOB_BY_DEGREE = "INCLUDE_JOB_BY_DEGREE";

